### ISSUE TITLE
how to download all emails?

### ISSUE THREAD

**Issue by ultrasaurus** [oaktown/calliope#20]
I thought `calliope download` would download all emails

but it doesn't.  I get this output...

```
2018/12/05 21:22:56 NextPageToken: 17070361527230096213
Estimate: 165
Messages found this page: 10
```

**Comment by jenmei** [comment]
Try typing `calliope help download`. To download 10,000 emails after October 1, you would do:
```bash
calliope -l 10000 -q "after:2018/10/01"
```

Let me know if the help could be improved.

**Comment by jenmei** [comment]
Can we close this?

**Comment by ultrasaurus** [comment]
added a PR with help tweak -- closing this as resolved!
